---
- name: Install Apache
  apt:
    name: apache2
    state: present
  become: yes

- name: Install PHP
  apt:
    name: php
    state: present
  become: yes

- name: Install php-mysql
  apt:
    name: php-mysql
    state: present
  become: yes
